# careers_data.py — Full Kenyan career database
# Source: KNBS Labour Force Survey, ILO ISCO-08, Kenya Vision 2030

CAREERS = [
    # ── Agriculture & Food ────────────────────────────────────────────
    {"id":"agronomist","title":"Agronomist","sector":"Agriculture & Food","sub":"Crop Science","risk":62,"workforce":82000,"is_technical":False,"roadmap_slug":None,
     "skills":["Soil & crop condition assessment","Community extension training","Climate adaptation planning","Pest & disease identification","Equipment operation","Post-harvest quality management"],
     "alt":["crop scientist","farm scientist"]},
    {"id":"agri-extension","title":"Agricultural Extension Officer","sector":"Agriculture & Food","sub":"Extension Services","risk":58,"workforce":45000,"is_technical":False,"roadmap_slug":None,
     "skills":["Community extension training","Field demonstration","Adult learning facilitation","Data collection","Report writing","Farmer group coordination"],
     "alt":["extension officer","agri officer"]},
    {"id":"farm-manager","title":"Farm Manager","sector":"Agriculture & Food","sub":"Farm Operations","risk":48,"workforce":110000,"is_technical":False,"roadmap_slug":None,
     "skills":["Farm operations planning","Staff management","Budget & cost control","Supply chain coordination","Equipment maintenance","Market linkage"],
     "alt":["farm supervisor","estate manager"]},
    {"id":"horticulturist","title":"Horticulturist","sector":"Agriculture & Food","sub":"Horticulture","risk":66,"workforce":38000,"is_technical":False,"roadmap_slug":None,
     "skills":["Crop lifecycle management","Irrigation management","Pest control","Post-harvest handling","Export compliance","Market scheduling"],
     "alt":["horticultural officer","floriculturist"]},
    {"id":"livestock-officer","title":"Livestock Officer","sector":"Agriculture & Food","sub":"Animal Husbandry","risk":52,"workforce":31000,"is_technical":False,"roadmap_slug":None,
     "skills":["Animal health assessment","Breeding programme management","Feed formulation","Disease surveillance","Farmer advisory","Record keeping"],
     "alt":["animal husbandry officer","livestock extension"]},
    {"id":"fisheries-officer","title":"Fisheries Officer","sector":"Agriculture & Food","sub":"Fisheries","risk":44,"workforce":18000,"is_technical":False,"roadmap_slug":None,
     "skills":["Fish stock assessment","Aquaculture management","Water quality monitoring","Community fishing training","Regulatory compliance","Market development"],
     "alt":["fisheries inspector","aquaculture officer"]},
    {"id":"food-scientist","title":"Food Scientist","sector":"Agriculture & Food","sub":"Food Technology","risk":55,"workforce":12000,"is_technical":False,"roadmap_slug":None,
     "skills":["Food safety compliance","Product formulation","Quality control","Lab analysis","HACCP implementation","R&D testing"],
     "alt":["food technologist","food safety officer"]},
    {"id":"agri-economist","title":"Agricultural Economist","sector":"Agriculture & Food","sub":"Agricultural Economics","risk":50,"workforce":8000,"is_technical":False,"roadmap_slug":None,
     "skills":["Market analysis","Policy research","Value chain analysis","Impact assessment","Farmer income modelling","Grant writing"],
     "alt":["farm economist","agribusiness analyst"]},
    {"id":"crop-scientist","title":"Crop Scientist","sector":"Agriculture & Food","sub":"Crop Science","risk":72,"workforce":28000,"is_technical":False,"roadmap_slug":None,
     "skills":["Crop research design","Genetic evaluation","Field trial management","Data analysis","Scientific writing","Seed system management"],
     "alt":["plant breeder","crop researcher"]},
    {"id":"irrigation-engineer","title":"Irrigation Engineer","sector":"Agriculture & Food","sub":"Irrigation","risk":38,"workforce":5000,"is_technical":True,"roadmap_slug":None,
     "skills":["Hydraulic design","Canal construction supervision","Irrigation scheduling","Water measurement","Farmer training","Environmental assessment"],
     "alt":["water engineer","drainage engineer"]},

    # ── Business & Finance ────────────────────────────────────────────
    {"id":"accountant","title":"Accountant","sector":"Business & Finance","sub":"Accounting","risk":79,"workforce":95000,"is_technical":False,"roadmap_slug":None,
     "skills":["Strategic financial judgement","Client relationship management","Complex regulatory interpretation","Audit oversight","Cross-cultural negotiation","Ethical advisory"],
     "alt":["CPA","certified accountant","accounts officer"]},
    {"id":"bank-teller","title":"Bank Teller","sector":"Business & Finance","sub":"Banking","risk":88,"workforce":42000,"is_technical":False,"roadmap_slug":None,
     "skills":["Customer de-escalation","Fraud detection instinct","Complex cash handling","Compliance judgement","Customer trust building","Supervisory handoff"],
     "alt":["cashier","banking officer","teller"]},
    {"id":"financial-analyst","title":"Financial Analyst","sector":"Business & Finance","sub":"Financial Analysis","risk":68,"workforce":28000,"is_technical":False,"roadmap_slug":None,
     "skills":["Investment thesis development","Qualitative market assessment","Client presentation","Risk narrative","Cross-functional advisory","Regulatory interpretation"],
     "alt":["investment analyst","finance officer"]},
    {"id":"hr-manager","title":"HR Manager","sector":"Business & Finance","sub":"Human Resources","risk":55,"workforce":35000,"is_technical":False,"roadmap_slug":None,
     "skills":["Conflict mediation","Organisational culture design","Talent judgement","Employment law interpretation","Leadership coaching","Change management"],
     "alt":["human resources manager","people manager","HR officer"]},
    {"id":"economist","title":"Economist","sector":"Business & Finance","sub":"Economics","risk":44,"workforce":12000,"is_technical":False,"roadmap_slug":None,
     "skills":["Economic narrative synthesis","Policy advisory","Stakeholder communication","Complex causal reasoning","Research design","Public testimony"],
     "alt":["economic analyst","economic advisor"]},
    {"id":"marketing-manager","title":"Marketing Manager","sector":"Business & Finance","sub":"Marketing","risk":52,"workforce":40000,"is_technical":False,"roadmap_slug":None,
     "skills":["Brand strategy","Consumer insight interpretation","Creative direction","Agency management","Budget allocation","Campaign P&L"],
     "alt":["brand manager","marketing officer","head of marketing"]},
    {"id":"auditor","title":"Auditor","sector":"Business & Finance","sub":"Audit","risk":74,"workforce":22000,"is_technical":False,"roadmap_slug":None,
     "skills":["Fraud investigation","Professional scepticism","Interview & interrogation","Complex sampling judgement","Report drafting","Regulatory liaison"],
     "alt":["internal auditor","external auditor","audit officer"]},
    {"id":"insurance-agent","title":"Insurance Agent","sector":"Business & Finance","sub":"Insurance","risk":82,"workforce":30000,"is_technical":False,"roadmap_slug":None,
     "skills":["Complex needs assessment","Trust-based relationship selling","Claims negotiation","Policy customisation","Referral network management","Complaint resolution"],
     "alt":["insurance broker","underwriter","claims officer"]},
    {"id":"supply-chain","title":"Supply Chain Manager","sector":"Business & Finance","sub":"Supply Chain","risk":60,"workforce":18000,"is_technical":False,"roadmap_slug":None,
     "skills":["Supplier relationship management","Disruption response","Contract negotiation","Cross-border logistics","Demand sensing","Cost optimisation"],
     "alt":["logistics manager","procurement manager","supply chain officer"]},
    {"id":"tax-consultant","title":"Tax Consultant","sector":"Business & Finance","sub":"Taxation","risk":76,"workforce":14000,"is_technical":False,"roadmap_slug":None,
     "skills":["Tax planning strategy","KRA dispute resolution","Client advisory","Regulatory interpretation","Transfer pricing","Cross-border tax structure"],
     "alt":["tax advisor","tax specialist","revenue officer"]},
    {"id":"procurement-officer","title":"Procurement Officer","sector":"Business & Finance","sub":"Procurement","risk":65,"workforce":28000,"is_technical":False,"roadmap_slug":None,
     "skills":["Supplier evaluation","Contract negotiation","Ethics & compliance","Market sourcing","Specification writing","Performance management"],
     "alt":["purchasing officer","buyer","tender officer"]},
    {"id":"office-admin","title":"Office Administrator","sector":"Business & Finance","sub":"Administration","risk":80,"workforce":60000,"is_technical":False,"roadmap_slug":None,
     "skills":["Executive support","Stakeholder coordination","Crisis scheduling","Confidentiality management","Event logistics","Multi-task prioritisation"],
     "alt":["PA","personal assistant","admin officer","secretary"]},
    {"id":"customer-service","title":"Customer Service Agent","sector":"Business & Finance","sub":"Customer Service","risk":85,"workforce":55000,"is_technical":False,"roadmap_slug":None,
     "skills":["Empathy under pressure","Complex complaint resolution","Escalation judgement","Product expertise","Customer retention","Cultural sensitivity"],
     "alt":["call centre agent","customer care","support agent"]},
    {"id":"biz-dev","title":"Business Development Manager","sector":"Business & Finance","sub":"Business Development","risk":46,"workforce":25000,"is_technical":False,"roadmap_slug":None,
     "skills":["Partnership strategy","Executive relationship building","Pitch & negotiation","Deal structuring","Market entry planning","Cross-cultural selling"],
     "alt":["BD manager","partnerships manager","sales director"]},

    # ── Healthcare ────────────────────────────────────────────────────
    {"id":"nurse","title":"Registered Nurse","sector":"Healthcare","sub":"Nursing","risk":15,"workforce":180000,"is_technical":False,"roadmap_slug":None,
     "skills":["Clinical diagnostic reasoning","Emergency patient triage","Empathetic communication","Ethical medical decision-making","Care team coordination","Procedural expertise"],
     "alt":["RN","nursing officer","staff nurse"]},
    {"id":"gp","title":"General Practitioner","sector":"Healthcare","sub":"Medicine","risk":12,"workforce":22000,"is_technical":False,"roadmap_slug":None,
     "skills":["Clinical diagnostic reasoning","Patient-centred consultation","Chronic disease management","Referral judgement","Preventive care","Community health leadership"],
     "alt":["doctor","medical officer","physician","GP"]},
    {"id":"pharmacist","title":"Pharmacist","sector":"Healthcare","sub":"Pharmacy","risk":42,"workforce":28000,"is_technical":False,"roadmap_slug":None,
     "skills":["Drug interaction assessment","Patient counselling","Prescription review","Adverse event detection","Stock & supply management","Regulatory compliance"],
     "alt":["pharmaceutical officer","pharmacy technician"]},
    {"id":"radiologist","title":"Radiologist","sector":"Healthcare","sub":"Radiology","risk":60,"workforce":4000,"is_technical":False,"roadmap_slug":None,
     "skills":["Complex image interpretation","Differential diagnosis","Procedural guidance","Multidisciplinary communication","Report quality assurance","Clinical correlation"],
     "alt":["radiology specialist","imaging specialist"]},
    {"id":"physiotherapist","title":"Physiotherapist","sector":"Healthcare","sub":"Physiotherapy","risk":22,"workforce":12000,"is_technical":False,"roadmap_slug":None,
     "skills":["Patient assessment","Manual therapy","Rehabilitation programme design","Pain management","Patient motivation","Outcome measurement"],
     "alt":["physical therapist","physio","rehab therapist"]},
    {"id":"lab-tech","title":"Medical Lab Technician","sector":"Healthcare","sub":"Laboratory","risk":55,"workforce":18000,"is_technical":False,"roadmap_slug":None,
     "skills":["Sample analysis quality control","Equipment calibration","Anomaly detection","Result interpretation","Lab safety compliance","Cross-check protocols"],
     "alt":["lab technician","clinical lab scientist","MLT"]},
    {"id":"clinical-officer","title":"Clinical Officer","sector":"Healthcare","sub":"Clinical Medicine","risk":20,"workforce":35000,"is_technical":False,"roadmap_slug":None,
     "skills":["Clinical assessment","Emergency management","Chronic disease care","Community health outreach","Patient education","Referral coordination"],
     "alt":["CO","clinical assistant"]},
    {"id":"dentist","title":"Dentist","sector":"Healthcare","sub":"Dentistry","risk":30,"workforce":6000,"is_technical":False,"roadmap_slug":None,
     "skills":["Oral examination","Complex extraction","Restorative procedures","Patient anxiety management","Preventive counselling","Infection control"],
     "alt":["dental surgeon","dental officer"]},
    {"id":"nutritionist","title":"Nutritionist","sector":"Healthcare","sub":"Nutrition","risk":35,"workforce":8000,"is_technical":False,"roadmap_slug":None,
     "skills":["Dietary assessment","Therapeutic nutrition planning","Patient behaviour change","Community nutrition education","Malnutrition management","Research translation"],
     "alt":["dietitian","nutrition officer"]},
    {"id":"public-health","title":"Public Health Officer","sector":"Healthcare","sub":"Public Health","risk":28,"workforce":15000,"is_technical":False,"roadmap_slug":None,
     "skills":["Epidemiological investigation","Community engagement","Programme design","Health system advocacy","Disease surveillance","Policy translation"],
     "alt":["public health specialist","health promotion officer"]},
    {"id":"surgeon","title":"Surgeon","sector":"Healthcare","sub":"Surgery","risk":18,"workforce":3000,"is_technical":False,"roadmap_slug":None,
     "skills":["Complex surgical decision-making","Intraoperative adaptation","Team leadership under pressure","Patient consent","Complication management","Teaching & mentorship"],
     "alt":["consultant surgeon","surgical specialist"]},
    {"id":"mental-health","title":"Mental Health Counsellor","sector":"Healthcare","sub":"Mental Health","risk":10,"workforce":5000,"is_technical":False,"roadmap_slug":None,
     "skills":["Therapeutic relationship building","Trauma-informed care","Crisis intervention","Treatment planning","Suicide risk assessment","Cultural competence"],
     "alt":["therapist","counsellor","psychotherapist"]},
    {"id":"midwife","title":"Midwife","sector":"Healthcare","sub":"Midwifery","risk":14,"workforce":25000,"is_technical":False,"roadmap_slug":None,
     "skills":["Labour monitoring","Emergency obstetric response","Newborn assessment","Mother empowerment","Breastfeeding support","Community outreach"],
     "alt":["registered midwife","maternity nurse"]},
    {"id":"chw","title":"Community Health Worker","sector":"Healthcare","sub":"Community Health","risk":18,"workforce":80000,"is_technical":False,"roadmap_slug":None,
     "skills":["Community trust building","Health education","Home visit assessment","Referral coordination","Data collection","Disease surveillance"],
     "alt":["CHW","community health volunteer"]},
    {"id":"ophthalmologist","title":"Ophthalmologist","sector":"Healthcare","sub":"Ophthalmology","risk":32,"workforce":2000,"is_technical":False,"roadmap_slug":None,
     "skills":["Clinical eye examination","Surgical procedures","Diagnosis of complex conditions","Patient counselling","Research & teaching","Equipment management"],
     "alt":["eye specialist","eye surgeon"]},

    # ── Information Technology ────────────────────────────────────────
    {"id":"software-dev","title":"Software Developer","sector":"Information Technology","sub":"Software Engineering","risk":28,"workforce":35000,"is_technical":True,"roadmap_slug":"full-stack",
     "skills":["System architecture design","Code review & mentorship","Security threat modelling","Product strategy thinking","Cross-functional leadership","Stakeholder communication"],
     "alt":["programmer","software engineer","coder","developer"]},
    {"id":"data-analyst","title":"Data Analyst","sector":"Information Technology","sub":"Data Analytics","risk":45,"workforce":18000,"is_technical":True,"roadmap_slug":"data-analyst",
     "skills":["Business problem translation","Insight communication","Stakeholder storytelling","Data quality judgement","Hypothesis formation","Strategic recommendation"],
     "alt":["analyst","business analyst","BI analyst"]},
    {"id":"cybersecurity","title":"Cybersecurity Analyst","sector":"Information Technology","sub":"Cybersecurity","risk":35,"workforce":8000,"is_technical":True,"roadmap_slug":"cyber-security",
     "skills":["Threat hunting","Incident response coordination","Security architecture review","Social engineering awareness","Red team strategy","Executive communication"],
     "alt":["security analyst","information security officer","SOC analyst"]},
    {"id":"sysadmin","title":"Systems Administrator","sector":"Information Technology","sub":"IT Operations","risk":58,"workforce":12000,"is_technical":True,"roadmap_slug":"system-design",
     "skills":["Infrastructure design","Capacity planning","Security hardening","Disaster recovery","Cross-team coordination","Vendor management"],
     "alt":["IT administrator","system administrator","IT officer"]},
    {"id":"ux-designer","title":"UX/UI Designer","sector":"Information Technology","sub":"Design","risk":40,"workforce":10000,"is_technical":True,"roadmap_slug":"ux-design",
     "skills":["User research facilitation","Design critique","Cross-functional collaboration","Accessibility advocacy","Prototype testing","Design system stewardship"],
     "alt":["UI designer","UX researcher","product designer"]},
    {"id":"network-engineer","title":"Network Engineer","sector":"Information Technology","sub":"Networking","risk":50,"workforce":9000,"is_technical":True,"roadmap_slug":"computer-science",
     "skills":["Network architecture design","Complex troubleshooting","Security implementation","Vendor negotiation","Capacity planning","Disaster recovery planning"],
     "alt":["network admin","telecoms engineer","network specialist"]},
    {"id":"devops","title":"DevOps Engineer","sector":"Information Technology","sub":"DevOps","risk":32,"workforce":5000,"is_technical":True,"roadmap_slug":"devops",
     "skills":["Infrastructure as code","Release strategy","Cross-team process design","Incident leadership","Cost optimisation","Developer experience design"],
     "alt":["site reliability engineer","SRE","platform engineer"]},
    {"id":"mobile-dev","title":"Mobile App Developer","sector":"Information Technology","sub":"Mobile Development","risk":30,"workforce":8000,"is_technical":True,"roadmap_slug":"android",
     "skills":["User-centred architecture","Platform strategy","Performance tuning","Cross-platform design","API design","App store optimisation"],
     "alt":["Android developer","iOS developer","flutter developer","app developer"]},
    {"id":"ai-ml","title":"AI/ML Engineer","sector":"Information Technology","sub":"AI & Machine Learning","risk":22,"workforce":4000,"is_technical":True,"roadmap_slug":"ai-data-scientist",
     "skills":["Problem framing for AI","Model evaluation judgement","Ethics & bias assessment","Research translation","Cross-domain application","Deployment strategy"],
     "alt":["machine learning engineer","AI engineer","data scientist"]},
    {"id":"it-support","title":"IT Support Specialist","sector":"Information Technology","sub":"IT Support","risk":65,"workforce":20000,"is_technical":True,"roadmap_slug":None,
     "skills":["Complex user problem solving","Hardware diagnosis","Security incident response","User training","Vendor liaison","Documentation"],
     "alt":["helpdesk","tech support","IT technician"]},
    {"id":"dba","title":"Database Administrator","sector":"Information Technology","sub":"Database Management","risk":55,"workforce":6000,"is_technical":True,"roadmap_slug":"postgresql-dba",
     "skills":["Performance tuning","Data architecture","Security hardening","Backup & recovery design","Capacity planning","Cross-team data governance"],
     "alt":["DBA","database engineer","data engineer"]},
    {"id":"product-manager","title":"Product Manager","sector":"Information Technology","sub":"Product Management","risk":38,"workforce":6000,"is_technical":True,"roadmap_slug":None,
     "skills":["Product strategy","Stakeholder alignment","User empathy","Prioritisation under ambiguity","Go-to-market planning","Metrics interpretation"],
     "alt":["PM","product owner"]},
    {"id":"qa-engineer","title":"QA Engineer","sector":"Information Technology","sub":"Quality Assurance","risk":48,"workforce":5000,"is_technical":True,"roadmap_slug":None,
     "skills":["Test strategy design","Edge case thinking","Process improvement","Defect communication","Risk-based testing","Automation oversight"],
     "alt":["tester","quality assurance analyst","test engineer"]},
    {"id":"blockchain-dev","title":"Blockchain Developer","sector":"Information Technology","sub":"Blockchain","risk":25,"workforce":2000,"is_technical":True,"roadmap_slug":None,
     "skills":["Smart contract audit","Cryptographic security","Protocol design","DeFi architecture","Cross-chain strategy","Community governance"],
     "alt":["web3 developer","smart contract developer","crypto developer"]},

    # ── Education ─────────────────────────────────────────────────────
    {"id":"primary-teacher","title":"Primary School Teacher","sector":"Education","sub":"Primary Education","risk":22,"workforce":290000,"is_technical":False,"roadmap_slug":None,
     "skills":["Adaptive and inclusive instruction","Student welfare mentorship","Curriculum localisation","Behavioural management","Parent engagement","Creative facilitation"],
     "alt":["class teacher","lower primary teacher","standard teacher"]},
    {"id":"secondary-teacher","title":"Secondary School Teacher","sector":"Education","sub":"Secondary Education","risk":25,"workforce":180000,"is_technical":False,"roadmap_slug":None,
     "skills":["Subject mastery & explanation","Exam coaching","Student mentorship","Curriculum design","Co-curricular leadership","Community trust"],
     "alt":["high school teacher","form teacher","subject teacher"]},
    {"id":"university-lecturer","title":"University Lecturer","sector":"Education","sub":"Higher Education","risk":28,"workforce":22000,"is_technical":False,"roadmap_slug":None,
     "skills":["Research design & execution","Knowledge translation","Student supervision","Grant acquisition","Academic peer engagement","Curriculum development"],
     "alt":["lecturer","professor","tutorial fellow","academic"]},
    {"id":"special-needs","title":"Special Needs Educator","sector":"Education","sub":"Special Education","risk":18,"workforce":8000,"is_technical":False,"roadmap_slug":None,
     "skills":["Individualised learning design","Behaviour intervention planning","Family partnership","Assistive technology use","Progress monitoring","Multi-agency coordination"],
     "alt":["special education teacher","SPED teacher"]},
    {"id":"librarian","title":"Librarian","sector":"Education","sub":"Library Science","risk":66,"workforce":5000,"is_technical":False,"roadmap_slug":None,
     "skills":["Collection curation","Research support","Information literacy teaching","Community programming","Archive management","Digital resource management"],
     "alt":["library officer","information specialist"]},
    {"id":"career-counsellor","title":"Career Counsellor","sector":"Education","sub":"Guidance & Counselling","risk":30,"workforce":6000,"is_technical":False,"roadmap_slug":None,
     "skills":["Individual psychoeducation","Career narrative coaching","Assessment interpretation","Crisis support","Parent advisory","Labour market knowledge"],
     "alt":["guidance counsellor","career advisor","student counsellor"]},
    {"id":"education-officer","title":"Education Officer","sector":"Education","sub":"Education Administration","risk":45,"workforce":12000,"is_technical":False,"roadmap_slug":None,
     "skills":["Policy implementation","School quality inspection","Teacher professional development","Community mobilisation","Data analysis & reporting","Resource allocation"],
     "alt":["DEO","district education officer","TSC officer"]},
    {"id":"ece-teacher","title":"Early Childhood Teacher","sector":"Education","sub":"Early Childhood","risk":20,"workforce":45000,"is_technical":False,"roadmap_slug":None,
     "skills":["Play-based learning facilitation","Child development observation","Parental partnership","Safeguarding","Creative programme design","Social-emotional support"],
     "alt":["ECD teacher","nursery teacher","kindergarten teacher","pre-school teacher"]},

    # ── Engineering ───────────────────────────────────────────────────
    {"id":"civil-engineer","title":"Civil Engineer","sector":"Engineering","sub":"Civil Engineering","risk":38,"workforce":18000,"is_technical":True,"roadmap_slug":None,
     "skills":["Structural integrity assessment","Construction site leadership","Client communication","Safety compliance","Environmental impact review","Contract management"],
     "alt":["civil engineering officer","site engineer"]},
    {"id":"electrical-engineer","title":"Electrical Engineer","sector":"Engineering","sub":"Electrical Engineering","risk":42,"workforce":14000,"is_technical":True,"roadmap_slug":None,
     "skills":["Electrical system design","Safety compliance","Project commissioning","Fault diagnosis","Client advisory","Energy optimisation"],
     "alt":["power engineer","electrical systems engineer"]},
    {"id":"mechanical-engineer","title":"Mechanical Engineer","sector":"Engineering","sub":"Mechanical Engineering","risk":45,"workforce":12000,"is_technical":True,"roadmap_slug":None,
     "skills":["Machine design","Failure analysis","Manufacturing oversight","R&D prototyping","Technical documentation","Cross-discipline coordination"],
     "alt":["mechanical engineering officer"]},
    {"id":"architect","title":"Architect","sector":"Engineering","sub":"Architecture","risk":40,"workforce":6000,"is_technical":True,"roadmap_slug":None,
     "skills":["Design vision & concept","Client relationship management","Regulatory navigation","Site problem-solving","Aesthetic judgement","Project leadership"],
     "alt":["architectural designer","building designer"]},
    {"id":"quantity-surveyor","title":"Quantity Surveyor","sector":"Engineering","sub":"Quantity Surveying","risk":55,"workforce":8000,"is_technical":True,"roadmap_slug":None,
     "skills":["Cost planning strategy","Contract negotiation","Value engineering","Dispute resolution","Procurement advisory","Risk identification"],
     "alt":["QS","cost estimator","cost consultant"]},
    {"id":"env-engineer","title":"Environmental Engineer","sector":"Engineering","sub":"Environmental Engineering","risk":32,"workforce":5000,"is_technical":True,"roadmap_slug":None,
     "skills":["EIA facilitation","Stakeholder consultation","Regulatory compliance","Remediation design","Policy interpretation","Scientific communication"],
     "alt":["environmental specialist","NEMA officer"]},

    # ── Skilled Trades ────────────────────────────────────────────────
    {"id":"electrician","title":"Electrician","sector":"Skilled Trades","sub":"Electrical Installation","risk":58,"workforce":45000,"is_technical":False,"roadmap_slug":None,
     "skills":["Complex fault diagnosis","Custom wiring design","Safety compliance","Client consultation","Blueprint interpretation","Apprentice supervision"],
     "alt":["electrical technician","wiring technician"]},
    {"id":"plumber","title":"Plumber","sector":"Skilled Trades","sub":"Plumbing","risk":44,"workforce":38000,"is_technical":False,"roadmap_slug":None,
     "skills":["Technical fault diagnosis","Custom installation","Safety compliance","Client scoping","Blueprint reading","Equipment maintenance"],
     "alt":["plumbing technician","pipefitter"]},
    {"id":"carpenter","title":"Carpenter","sector":"Skilled Trades","sub":"Carpentry","risk":48,"workforce":55000,"is_technical":False,"roadmap_slug":None,
     "skills":["Custom fabrication","Structural assessment","Client design consultation","Material selection","Finishing quality control","Site safety"],
     "alt":["joiner","woodworker","furniture maker"]},
    {"id":"welder","title":"Welder","sector":"Skilled Trades","sub":"Welding","risk":62,"workforce":28000,"is_technical":False,"roadmap_slug":None,
     "skills":["Complex joint technique","Material compatibility","Quality inspection","Blueprint reading","Safety compliance","Custom fabrication"],
     "alt":["metal fabricator","boilermaker"]},
    {"id":"auto-mechanic","title":"Auto Mechanic","sector":"Skilled Trades","sub":"Automotive","risk":50,"workforce":65000,"is_technical":False,"roadmap_slug":None,
     "skills":["Diagnostic fault reasoning","Engine overhaul","Client communication","Parts sourcing","Electrical systems","EV adaptation"],
     "alt":["motor vehicle technician","mechanic","garage technician"]},
    {"id":"mason","title":"Mason","sector":"Skilled Trades","sub":"Masonry","risk":52,"workforce":80000,"is_technical":False,"roadmap_slug":None,
     "skills":["Structural bricklaying","Concrete finishing","Structural assessment","Site safety","Blueprint reading","Client liaison"],
     "alt":["bricklayer","construction worker","fundi"]},
    {"id":"tailor","title":"Tailor","sector":"Skilled Trades","sub":"Tailoring","risk":60,"workforce":120000,"is_technical":False,"roadmap_slug":None,
     "skills":["Custom garment design","Client fitting & consultation","Pattern modification","Quality finishing","Trend interpretation","Business management"],
     "alt":["dressmaker","seamstress","fundi wa nguo"]},
    {"id":"hvac","title":"HVAC Technician","sector":"Skilled Trades","sub":"HVAC","risk":52,"workforce":8000,"is_technical":False,"roadmap_slug":None,
     "skills":["System design","Refrigerant handling","Fault diagnosis","Preventive maintenance","Energy optimisation","Safety compliance"],
     "alt":["air conditioning technician","refrigeration technician"]},

    # ── Media & Creative ──────────────────────────────────────────────
    {"id":"journalist","title":"Journalist","sector":"Media & Creative","sub":"Journalism","risk":55,"workforce":12000,"is_technical":False,"roadmap_slug":None,
     "skills":["Investigative source cultivation","Narrative framing","Live production management","Editorial judgement","Audience strategy","Accountability journalism"],
     "alt":["reporter","correspondent","editor","news anchor"]},
    {"id":"graphic-designer","title":"Graphic Designer","sector":"Media & Creative","sub":"Graphic Design","risk":58,"workforce":10000,"is_technical":False,"roadmap_slug":None,
     "skills":["Creative direction","Brand strategy","Client relationship","Conceptual thinking","Art direction","Production oversight"],
     "alt":["visual designer","creative designer","digital designer"]},
    {"id":"photographer","title":"Photographer","sector":"Media & Creative","sub":"Photography","risk":48,"workforce":8000,"is_technical":False,"roadmap_slug":None,
     "skills":["Visual storytelling","Client relationship","Style & aesthetic direction","Location & lighting mastery","Post-processing artistry","Business management"],
     "alt":["photo artist","photojournalist","commercial photographer"]},
    {"id":"social-media-manager","title":"Social Media Manager","sector":"Media & Creative","sub":"Digital Marketing","risk":65,"workforce":8000,"is_technical":False,"roadmap_slug":None,
     "skills":["Community voice & culture","Crisis communication","Influencer relationship","Real-time content judgement","Platform strategy","Brand protection"],
     "alt":["social media officer","digital marketing manager","community manager"]},
    {"id":"copywriter","title":"Copywriter","sector":"Media & Creative","sub":"Copywriting","risk":62,"workforce":5000,"is_technical":False,"roadmap_slug":None,
     "skills":["Brand voice development","Persuasion strategy","Campaign concept","Client collaboration","Cultural nuance","Creative briefing"],
     "alt":["content writer","advertising writer","creative writer"]},
    {"id":"pr-specialist","title":"PR Specialist","sector":"Media & Creative","sub":"Public Relations","risk":50,"workforce":4000,"is_technical":False,"roadmap_slug":None,
     "skills":["Media relationship management","Crisis communication","Message strategy","Spokesperson coaching","Narrative development","Reputation management"],
     "alt":["PR officer","communications officer","public affairs"]},
    {"id":"videographer","title":"Videographer","sector":"Media & Creative","sub":"Video Production","risk":45,"workforce":6000,"is_technical":False,"roadmap_slug":None,
     "skills":["Cinematography","Narrative direction","Client management","Multi-camera operation","Color grading artistry","Post-production judgement"],
     "alt":["video producer","filmmaker","cinematographer"]},
    {"id":"animator","title":"Animator","sector":"Media & Creative","sub":"Animation","risk":45,"workforce":3000,"is_technical":True,"roadmap_slug":None,
     "skills":["Character & world design","Motion principles","Art direction","Client communication","Visual storytelling","Pipeline management"],
     "alt":["motion graphics designer","VFX artist","2D/3D animator"]},

    # ── Legal & Governance ────────────────────────────────────────────
    {"id":"lawyer","title":"Lawyer","sector":"Legal & Governance","sub":"Law","risk":35,"workforce":22000,"is_technical":False,"roadmap_slug":None,
     "skills":["Legal reasoning & argumentation","Client advocacy","Courtroom strategy","Regulatory interpretation","Negotiation & mediation","Ethical judgement"],
     "alt":["advocate","attorney","legal officer","solicitor"]},
    {"id":"judge","title":"Judge","sector":"Legal & Governance","sub":"Judiciary","risk":20,"workforce":3000,"is_technical":False,"roadmap_slug":None,
     "skills":["Judicial impartiality","Legal reasoning","Evidence assessment","Sentence proportionality","Procedural integrity","Constitutional interpretation"],
     "alt":["magistrate","judicial officer"]},
    {"id":"paralegal","title":"Paralegal","sector":"Legal & Governance","sub":"Legal Support","risk":65,"workforce":6000,"is_technical":False,"roadmap_slug":None,
     "skills":["Legal research","Document preparation","Court filing","Client intake","Case management","Regulatory tracking"],
     "alt":["legal assistant","legal clerk"]},
    {"id":"civil-servant","title":"Civil Servant","sector":"Legal & Governance","sub":"Public Administration","risk":58,"workforce":180000,"is_technical":False,"roadmap_slug":None,
     "skills":["Policy implementation","Stakeholder engagement","Public accountability","Interagency coordination","Budget management","Service delivery"],
     "alt":["government officer","public servant","ministry officer"]},
    {"id":"policy-analyst","title":"Policy Analyst","sector":"Legal & Governance","sub":"Policy","risk":42,"workforce":5000,"is_technical":False,"roadmap_slug":None,
     "skills":["Policy research design","Stakeholder consultation","Economic modelling","Report writing","Parliamentary advisory","Evidence synthesis"],
     "alt":["policy officer","policy researcher","policy advisor"]},
    {"id":"compliance-officer","title":"Compliance Officer","sector":"Legal & Governance","sub":"Compliance","risk":60,"workforce":6000,"is_technical":False,"roadmap_slug":None,
     "skills":["Regulatory interpretation","Internal investigation","Risk assessment","Policy design","Training delivery","Whistleblower management"],
     "alt":["regulatory officer","risk & compliance officer"]},

    # ── Transport & Logistics ─────────────────────────────────────────
    {"id":"truck-driver","title":"Truck Driver","sector":"Transport & Logistics","sub":"Road Freight","risk":82,"workforce":120000,"is_technical":False,"roadmap_slug":None,
     "skills":["Adaptive long-distance navigation","Preventive maintenance judgement","Emergency handling","Load compliance","Border & customs liaison","Multi-stop coordination"],
     "alt":["HGV driver","lorry driver","freight driver"]},
    {"id":"boda-boda","title":"Boda Boda Operator","sector":"Transport & Logistics","sub":"Motorcycle Transport","risk":70,"workforce":850000,"is_technical":False,"roadmap_slug":None,
     "skills":["Customer relationship","Local route knowledge","Safety judgement","Emergency handling","Digital platform navigation","Community trust"],
     "alt":["motorcycle taxi","courier rider","delivery rider"]},
    {"id":"pilot","title":"Pilot","sector":"Transport & Logistics","sub":"Aviation","risk":32,"workforce":2000,"is_technical":True,"roadmap_slug":None,
     "skills":["Complex airspace decision-making","Crew resource management","Emergency protocol execution","Weather assessment","Passenger leadership","Regulatory compliance"],
     "alt":["commercial pilot","flight officer","first officer","captain"]},
    {"id":"logistics-coordinator","title":"Logistics Coordinator","sector":"Transport & Logistics","sub":"Logistics","risk":62,"workforce":15000,"is_technical":False,"roadmap_slug":None,
     "skills":["Multi-modal coordination","Supplier relationship management","Customs clearance","Disruption response","Cost optimisation","Client communication"],
     "alt":["logistics officer","shipping coordinator","freight coordinator"]},
    {"id":"matatu-driver","title":"Matatu Driver","sector":"Transport & Logistics","sub":"Public Transport","risk":78,"workforce":200000,"is_technical":False,"roadmap_slug":None,
     "skills":["Route navigation","Passenger handling","Mechanical awareness","Time management","Revenue maximisation","Safety compliance"],
     "alt":["PSV driver","bus driver","public transport driver"]},
    {"id":"warehouse-manager","title":"Warehouse Manager","sector":"Transport & Logistics","sub":"Warehousing","risk":55,"workforce":12000,"is_technical":False,"roadmap_slug":None,
     "skills":["Operations leadership","Inventory accuracy","Staff management","Safety compliance","Client relationship","Technology adoption"],
     "alt":["warehouse supervisor","distribution centre manager","store manager"]},
    {"id":"aviation-tech","title":"Aviation Technician","sector":"Transport & Logistics","sub":"Aviation Maintenance","risk":44,"workforce":4000,"is_technical":True,"roadmap_slug":None,
     "skills":["Aircraft systems diagnosis","Regulatory compliance","Safety-critical decision-making","Technical documentation","Team coordination","Continuous learning"],
     "alt":["aircraft engineer","AME","aircraft maintenance engineer"]},

    # ── Hospitality & Tourism ─────────────────────────────────────────
    {"id":"hotel-manager","title":"Hotel Manager","sector":"Hospitality & Tourism","sub":"Hotel Management","risk":40,"workforce":8000,"is_technical":False,"roadmap_slug":None,
     "skills":["Guest experience design","Staff leadership","Revenue management","Crisis de-escalation","Community partnership","Brand stewardship"],
     "alt":["hotel general manager","GM","resort manager","lodge manager"]},
    {"id":"chef","title":"Chef","sector":"Hospitality & Tourism","sub":"Culinary Arts","risk":35,"workforce":18000,"is_technical":False,"roadmap_slug":None,
     "skills":["Culinary creativity & technique","Kitchen leadership","Menu engineering","Cost control","Supplier relationship","Cultural food adaptation"],
     "alt":["cook","head chef","executive chef","sous chef"]},
    {"id":"tour-guide","title":"Tour Guide","sector":"Hospitality & Tourism","sub":"Tourism","risk":22,"workforce":12000,"is_technical":False,"roadmap_slug":None,
     "skills":["Cultural storytelling","Emergency response","Guest psychology","Local knowledge","Language facilitation","Itinerary adaptation"],
     "alt":["safari guide","tourist guide","tour leader"]},
    {"id":"front-desk","title":"Front Desk Officer","sector":"Hospitality & Tourism","sub":"Front Office","risk":70,"workforce":20000,"is_technical":False,"roadmap_slug":None,
     "skills":["Guest experience recovery","Complaint resolution","Upselling through service","Multi-task coordination","VIP relationship","Cultural sensitivity"],
     "alt":["receptionist","hotel receptionist","front office agent"]},
    {"id":"event-planner","title":"Event Planner","sector":"Hospitality & Tourism","sub":"Events","risk":38,"workforce":6000,"is_technical":False,"roadmap_slug":None,
     "skills":["Creative concept design","Vendor negotiation","Crisis management","Client vision translation","Multi-stakeholder coordination","Budget optimisation"],
     "alt":["event coordinator","events manager","wedding planner"]},
    {"id":"travel-agent","title":"Travel Agent","sector":"Hospitality & Tourism","sub":"Travel","risk":75,"workforce":5000,"is_technical":False,"roadmap_slug":None,
     "skills":["Complex itinerary design","Client relationship","Destination expertise","Crisis travel support","Visa & documentation","Corporate travel management"],
     "alt":["travel consultant","ticketing agent","travel coordinator"]},

    # ── Social & Community ────────────────────────────────────────────
    {"id":"social-worker","title":"Social Worker","sector":"Social & Community","sub":"Social Work","risk":18,"workforce":15000,"is_technical":False,"roadmap_slug":None,
     "skills":["Trauma-informed case management","Conflict resolution","Community trust building","Cultural mediation","Programme impact assessment","Crisis intervention"],
     "alt":["community worker","welfare officer","case manager"]},
    {"id":"ngo-officer","title":"NGO Programme Officer","sector":"Social & Community","sub":"Development","risk":35,"workforce":20000,"is_technical":False,"roadmap_slug":None,
     "skills":["Programme design & M&E","Stakeholder engagement","Grant writing","Community mobilisation","Donor reporting","Advocacy & policy influencing"],
     "alt":["development officer","project officer","field officer"]},
    {"id":"psychologist","title":"Psychologist","sector":"Social & Community","sub":"Psychology","risk":15,"workforce":4000,"is_technical":False,"roadmap_slug":None,
     "skills":["Psychological assessment","Therapeutic relationship","Crisis intervention","Cultural competence","Research & report writing","Multidisciplinary collaboration"],
     "alt":["clinical psychologist","educational psychologist"]},
    {"id":"youth-worker","title":"Youth Worker","sector":"Social & Community","sub":"Youth Development","risk":22,"workforce":8000,"is_technical":False,"roadmap_slug":None,
     "skills":["Youth engagement & trust","Group facilitation","Programme design","Safeguarding","Mentorship","Community partnership"],
     "alt":["youth officer","youth programme coordinator"]},
    {"id":"religious-leader","title":"Religious Leader","sector":"Social & Community","sub":"Religion","risk":12,"workforce":50000,"is_technical":False,"roadmap_slug":None,
     "skills":["Spiritual counsel","Community leadership","Conflict mediation","Pastoral care","Cultural custodianship","Public speaking"],
     "alt":["pastor","imam","priest","sheikh","reverend"]},
    {"id":"community-dev","title":"Community Development Officer","sector":"Social & Community","sub":"Community Development","risk":28,"workforce":12000,"is_technical":False,"roadmap_slug":None,
     "skills":["Community needs assessment","Participatory planning","Resource mobilisation","Capacity building","Multi-agency coordination","M&E"],
     "alt":["community officer","social development officer"]},

    # ── Science & Research ────────────────────────────────────────────
    {"id":"biologist","title":"Biologist","sector":"Science & Research","sub":"Biology","risk":40,"workforce":5000,"is_technical":True,"roadmap_slug":None,
     "skills":["Experimental design","Field sampling","Data interpretation","Scientific writing","Lab safety","Research communication"],
     "alt":["wildlife biologist","marine biologist","conservation biologist"]},
    {"id":"chemist","title":"Chemist","sector":"Science & Research","sub":"Chemistry","risk":45,"workforce":4000,"is_technical":True,"roadmap_slug":None,
     "skills":["Analytical method development","Lab management","Quality assurance","Regulatory compliance","Research design","Technical reporting"],
     "alt":["analytical chemist","industrial chemist","lab chemist"]},
    {"id":"statistician","title":"Statistician","sector":"Science & Research","sub":"Statistics","risk":50,"workforce":5000,"is_technical":True,"roadmap_slug":None,
     "skills":["Survey design","Statistical modelling","Data quality judgement","Policy translation","Report writing","Stakeholder communication"],
     "alt":["data statistician","survey statistician","biostatistician"]},
    {"id":"meteorologist","title":"Meteorologist","sector":"Science & Research","sub":"Meteorology","risk":48,"workforce":2000,"is_technical":True,"roadmap_slug":None,
     "skills":["Forecast interpretation","Climate advisory","Disaster risk communication","Stakeholder briefing","Field observation","Model validation"],
     "alt":["weather officer","climate scientist","forecast officer"]},
    {"id":"veterinarian","title":"Veterinarian","sector":"Science & Research","sub":"Veterinary Medicine","risk":36,"workforce":8000,"is_technical":False,"roadmap_slug":None,
     "skills":["Animal clinical assessment","Surgical procedures","Disease investigation","One Health advisory","Farmer communication","Drug prescription"],
     "alt":["vet","animal doctor","vet officer"]},
    {"id":"geologist","title":"Geologist","sector":"Science & Research","sub":"Geology","risk":42,"workforce":3000,"is_technical":True,"roadmap_slug":None,
     "skills":["Geological mapping","Field investigation","Rock & mineral analysis","Environmental assessment","Report writing","Stakeholder briefing"],
     "alt":["mining geologist","petroleum geologist","hydrogeologist"]},
    {"id":"mathematician","title":"Mathematician","sector":"Science & Research","sub":"Mathematics","risk":35,"workforce":4000,"is_technical":True,"roadmap_slug":None,
     "skills":["Mathematical modelling","Algorithm design","Research communication","Interdisciplinary translation","Teaching & mentorship","Problem framing"],
     "alt":["applied mathematician","actuary","operations researcher"]},

    # ── Informal Economy ──────────────────────────────────────────────
    {"id":"mpesa-agent","title":"M-Pesa Agent","sector":"Informal Economy","sub":"Mobile Money","risk":88,"workforce":250000,"is_technical":False,"roadmap_slug":None,
     "skills":["Customer trust & relationship","Cash liquidity management","Fraud detection instinct","Community problem-solving","Digital platform navigation","Business management"],
     "alt":["mobile money agent","fintech agent","Airtel Money agent"]},
    {"id":"jua-kali","title":"Jua Kali Artisan","sector":"Informal Economy","sub":"Informal Manufacturing","risk":45,"workforce":400000,"is_technical":False,"roadmap_slug":None,
     "skills":["Custom fabrication","Material resourcefulness","Client negotiation","Quality without tools","Business resilience","Apprentice training"],
     "alt":["informal artisan","metalworker","roadside mechanic","fundi"]},
    {"id":"market-trader","title":"Market Trader","sector":"Informal Economy","sub":"Retail Trade","risk":60,"workforce":1200000,"is_technical":False,"roadmap_slug":None,
     "skills":["Market price intelligence","Supplier negotiation","Customer relationship","Credit & cash management","Stock judgement","Community network"],
     "alt":["mama mboga","trader","vendor","hawker","market seller"]},
    {"id":"food-vendor","title":"Street Food Vendor","sector":"Informal Economy","sub":"Food Vending","risk":38,"workforce":500000,"is_technical":False,"roadmap_slug":None,
     "skills":["Culinary skill & recipe","Customer loyalty building","Location & timing strategy","Hygiene compliance","Cost management","Product innovation"],
     "alt":["food kiosk owner","mama fry","nyama choma vendor","mandazi seller"]},
    {"id":"domestic-worker","title":"Domestic Worker","sector":"Informal Economy","sub":"Domestic Services","risk":30,"workforce":800000,"is_technical":False,"roadmap_slug":None,
     "skills":["Child & elder care","Household management","Trust & discretion","Emotional support","Flexible problem-solving","Cultural sensitivity"],
     "alt":["house help","nanny","housekeeper","house girl","domestic helper"]},
    {"id":"security-guard","title":"Watchman / Security Guard","sector":"Informal Economy","sub":"Security","risk":72,"workforce":300000,"is_technical":False,"roadmap_slug":None,
     "skills":["Threat assessment","Conflict de-escalation","Access control judgement","Emergency response","Surveillance vigilance","Community liaison"],
     "alt":["guard","watchman","security officer","askari"]},
]

# Sector-level threat data (3 threats per sector, used in Round 1)
SECTOR_THREATS = {
    "Agriculture & Food": [
        {"title":"AI crop disease detection","body":"Mobile apps like PlantVillage use computer vision to diagnose crop diseases from a photo with 99% accuracy — replacing initial diagnostic advisory visits for extension officers.","damage":22},
        {"title":"Precision agriculture automation","body":"IoT soil sensors and drone imagery replace manual field scouting — reducing hands-on field visits by up to 60% across large-scale farms.","damage":18},
        {"title":"AI-generated extension reports","body":"Farm management AI tools auto-generate planting schedules, yield forecasts, and management reports — removing administrative fieldwork from extension roles.","damage":16},
    ],
    "Business & Finance": [
        {"title":"Automated bookkeeping & invoicing","body":"AI tools like QuickBooks AI and Microsoft Copilot now handle 90% of routine transaction categorisation, reconciliation, and invoice processing — eliminating 4–6 hours of daily manual accounting work.","damage":28},
        {"title":"AI-generated financial reports","body":"Claude, ChatGPT, and Copilot generate board-ready financial summaries and management accounts from raw data in seconds — replacing junior analyst report-writing.","damage":22},
        {"title":"Regulatory compliance automation","body":"RegTech platforms auto-monitor KRA filings, flag compliance issues, and pre-fill tax returns — tasks that previously required dedicated compliance staff and accountants.","damage":20},
    ],
    "Healthcare": [
        {"title":"AI diagnostic imaging analysis","body":"Radiology AI reads chest X-rays, ECGs, and retinal scans with specialist-level accuracy — flagging 94% of abnormalities before human review, reducing routine radiologist workload.","damage":18},
        {"title":"Automated patient intake & triage","body":"AI chatbots and symptom checkers now handle initial triage, history-taking, and appointment scheduling — reducing admin nursing and front-desk workload significantly.","damage":14},
        {"title":"Clinical documentation AI","body":"Tools like Nuance DAX auto-generate clinical notes from doctor-patient conversations in real time — saving 2–3 hours of charting per shift for clinical staff.","damage":12},
    ],
    "Information Technology": [
        {"title":"AI pair programming at scale","body":"GitHub Copilot and Claude Code now write 40–60% of boilerplate and standard function code automatically — shifting developer value entirely to architecture, review, and complex problem-solving.","damage":18},
        {"title":"Automated testing & QA","body":"AI-powered test generation tools (Testim, Mabl) write and maintain test suites automatically — reducing manual QA engineering time by up to 70%.","damage":16},
        {"title":"Low-code platform proliferation","body":"Bubble, Webflow, and n8n let non-technical users build apps and automations — reducing demand for junior developers and routine IT support specialists in Kenya.","damage":14},
    ],
    "Education": [
        {"title":"AI tutoring & personalised learning","body":"Khan Academy's Khanmigo and similar tools provide 1-on-1 AI tutoring at scale — reducing demand for supplementary teaching, private tutoring, and homework support roles.","damage":14},
        {"title":"Automated essay grading","body":"AI tools grade and provide detailed written feedback on assignments in seconds — cutting marking time that currently consumes 30% of a teacher's working week.","damage":12},
        {"title":"AI curriculum content generation","body":"ChatGPT and Canva AI generate lesson plans, worksheets, and presentations in minutes — reducing lesson preparation time by 60% and threatening content creation roles.","damage":10},
    ],
    "Engineering": [
        {"title":"Generative design & simulation","body":"AI tools like Autodesk Generative Design auto-produce optimised structural designs from parameters — reducing the time junior engineers spend on design iteration by 70%.","damage":20},
        {"title":"AI construction project management","body":"Platforms like Buildots use computer vision to monitor construction site progress in real time — replacing manual site inspection and progress reporting.","damage":16},
        {"title":"Automated structural calculations","body":"AI-powered structural analysis tools run thousands of load case scenarios instantly — removing routine calculation work from civil and structural engineering roles.","damage":14},
    ],
    "Skilled Trades": [
        {"title":"AI fault diagnosis tools","body":"OBD AI systems and predictive maintenance platforms diagnose mechanical and electrical faults from sensor data alone — reducing diagnostic time and specialist knowledge requirements.","damage":20},
        {"title":"Robotic welding & fabrication","body":"Industrial welding robots now handle 80% of standard joint types in manufacturing — displacing routine welding and fabrication work while increasing production speed.","damage":18},
        {"title":"Automated construction equipment","body":"AI-controlled machinery for concrete placement, bricklaying, and finishing is entering the Kenyan construction market — reducing demand for routine trade labour.","damage":16},
    ],
    "Media & Creative": [
        {"title":"AI article & copy generation","body":"Claude, ChatGPT, and Jasper AI generate news summaries, press releases, and marketing copy at scale — competing directly with junior journalists and copywriters across Kenya.","damage":24},
        {"title":"AI image & video generation","body":"Midjourney, Sora, and Adobe Firefly produce commercial-quality images and video in seconds — disrupting photography, videography, illustration, and stock media roles.","damage":20},
        {"title":"Automated social media management","body":"AI tools generate, schedule, and A/B test social media content automatically — replacing the routine content production and scheduling work of social media managers.","damage":18},
    ],
    "Legal & Governance": [
        {"title":"AI legal document analysis","body":"Tools like Harvey AI and Casetext read, summarise, and extract clauses from contracts and case law in seconds — replacing junior associate document review work.","damage":22},
        {"title":"Automated compliance monitoring","body":"AI platforms continuously monitor regulatory changes, flag non-compliance, and generate compliance reports — reducing demand for compliance officer routine monitoring work.","damage":18},
        {"title":"AI court document drafting","body":"LLMs draft motions, pleadings, and routine correspondence with high accuracy — shifting paralegal and junior lawyer time to review rather than creation.","damage":16},
    ],
    "Transport & Logistics": [
        {"title":"Autonomous vehicle technology","body":"Tesla FSD and Waymo are advancing toward commercial deployment — with projections suggesting 40% of long-haul freight routes could be automated by 2030, directly threatening driving roles.","damage":32},
        {"title":"AI route optimisation platforms","body":"Google Maps AI and Circuit continuously optimise delivery and passenger routes in real time — reducing the unique value of local route knowledge and manual dispatch decisions.","damage":22},
        {"title":"Ride-hailing full algorithmic control","body":"Uber and Bolt algorithms now fully control pricing, dispatch, routing, and customer matching — drivers execute decisions made entirely by AI, reducing professional driving to physical execution only.","damage":18},
    ],
    "Hospitality & Tourism": [
        {"title":"AI concierge & booking systems","body":"AI-powered virtual concierges handle guest inquiries, restaurant bookings, activity planning, and complaints 24/7 — replacing front desk and concierge roles in higher-end hotels.","damage":22},
        {"title":"Dynamic pricing automation","body":"AI revenue management systems set room rates in real time based on demand signals — removing the need for dedicated revenue manager and pricing analyst roles.","damage":16},
        {"title":"AI translation & language apps","body":"Real-time AI translation (Google Translate, DeepL) removes the language barrier advantage of human guides — reducing the unique value of multilingual hospitality staff.","damage":14},
    ],
    "Social & Community": [
        {"title":"AI case management tools","body":"Social care platforms with AI automate case assessment, risk scoring, and intervention recommendation — reducing caseload administrative burden but also displacing routine assessment roles.","damage":14},
        {"title":"AI grant writing & donor reporting","body":"ChatGPT and Claude generate first-draft grant proposals and donor reports — reducing the writing time for NGO programme officers by 60% while increasing competition for funds.","damage":12},
        {"title":"Automated community data collection","body":"Mobile survey platforms with AI analysis (KoboToolbox AI, ODK) automate community needs assessment data collection and analysis — reducing demand for field data collection roles.","damage":10},
    ],
    "Science & Research": [
        {"title":"AI literature review & synthesis","body":"Tools like Elicit and Consensus AI read thousands of research papers and synthesise findings in minutes — replacing weeks of manual literature review for junior researchers.","damage":20},
        {"title":"Automated lab analysis","body":"AI-powered chromatography, sequencing, and imaging analysis tools produce results and flag anomalies automatically — reducing hands-on lab analysis time for technicians.","damage":18},
        {"title":"AI hypothesis generation","body":"Scientific AI tools generate novel hypotheses from existing datasets — shifting researcher value from data gathering to experimental design and interpretation.","damage":14},
    ],
    "Informal Economy": [
        {"title":"Super-app platform consolidation","body":"M-Pesa, Airtel Money, and super-apps are automating float management, compliance, and transaction routing — reducing the unique value of human agents in routine float and transaction handling.","damage":28},
        {"title":"E-commerce platform displacement","body":"Jumia, Copia, and WhatsApp Commerce enable consumers to order directly from suppliers — bypassing market traders and reducing the need for physical market intermediaries.","damage":24},
        {"title":"AI pricing & demand prediction","body":"Platform algorithms predict product demand and set optimal prices in real time — removing the market intelligence advantage that experienced traders have built over years.","damage":18},
    ],
}

# Sector-level skill sets (for skill card combat, Friend 2 screen)
SECTOR_SKILLS = {sector: [c["skills"] for c in CAREERS if c["sector"] == sector][0]
                 for sector in set(c["sector"] for c in CAREERS)}